CREATE TABLE IF NOT EXISTS knowledge_wiki_sources (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    source_key VARCHAR(512) NOT NULL DEFAULT '', source_type VARCHAR(32) NOT NULL DEFAULT '',
    raw_path VARCHAR(1024) NOT NULL DEFAULT '', current_version_id BIGINT UNSIGNED NULL,
    active_job_id BIGINT UNSIGNED NULL, content_sha256 CHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(24) NOT NULL DEFAULT 'pending', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), deleted_at DATETIME(3) NULL,
    UNIQUE KEY uk_wiki_source (tenant_id, source_key)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_source_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    source_id BIGINT UNSIGNED NOT NULL, sha256 CHAR(64) NOT NULL DEFAULT '', size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    snapshot_path VARCHAR(1024) NOT NULL DEFAULT '', schema_version VARCHAR(32) NOT NULL DEFAULT 'v1',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL, UNIQUE KEY uk_wiki_source_version (tenant_id, source_id, sha256)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_source_chunks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    version_id BIGINT UNSIGNED NOT NULL, parent_chunk_id BIGINT UNSIGNED NULL, ordinal INT UNSIGNED NOT NULL DEFAULT 0,
    start_offset BIGINT UNSIGNED NOT NULL DEFAULT 0, end_offset BIGINT UNSIGNED NOT NULL DEFAULT 0,
    summary_path VARCHAR(1024) NOT NULL DEFAULT '', summary_sha256 CHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL, UNIQUE KEY uk_wiki_chunk (tenant_id, version_id, ordinal)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_compile_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    source_ids_json JSON NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'pending', stage VARCHAR(32) NOT NULL DEFAULT 'queued',
    force_compile BOOLEAN NOT NULL DEFAULT FALSE, active_key CHAR(64) NULL, lease_owner VARCHAR(128) NOT NULL DEFAULT '',
    lease_expires_at DATETIME(3) NULL, attempt INT UNSIGNED NOT NULL DEFAULT 0, cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    error_message VARCHAR(2048) NOT NULL DEFAULT '', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), deleted_at DATETIME(3) NULL,
    UNIQUE KEY uk_wiki_job_active (active_key)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_topics (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, topic_id VARCHAR(64) NOT NULL DEFAULT '', tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    canonical_key VARCHAR(512) NOT NULL DEFAULT '', title VARCHAR(512) NOT NULL DEFAULT '', aliases_json JSON NOT NULL,
    entity_names_json JSON NOT NULL, concept_names_json JSON NOT NULL, summary TEXT NOT NULL,
    generation_fingerprint CHAR(64) NOT NULL DEFAULT '', status VARCHAR(24) NOT NULL DEFAULT 'pending',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL, UNIQUE KEY uk_wiki_topic_id (topic_id), UNIQUE KEY uk_wiki_topic_key (tenant_id, canonical_key)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_topic_evidence (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    topic_id VARCHAR(64) NOT NULL DEFAULT '', source_id BIGINT UNSIGNED NOT NULL, source_version_id BIGINT UNSIGNED NOT NULL,
    chunk_ordinal INT UNSIGNED NOT NULL DEFAULT 0, evidence_start BIGINT UNSIGNED NOT NULL DEFAULT 0,
    evidence_end BIGINT UNSIGNED NOT NULL DEFAULT 0, kind VARCHAR(24) NOT NULL DEFAULT 'context',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uk_wiki_topic_evidence (tenant_id, topic_id, source_id, source_version_id, chunk_ordinal, evidence_start, evidence_end)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_pages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, page_id VARCHAR(64) NOT NULL DEFAULT '', tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    page_type VARCHAR(24) NOT NULL DEFAULT 'source', title VARCHAR(512) NOT NULL DEFAULT '', aliases_json JSON NOT NULL,
    language VARCHAR(16) NOT NULL DEFAULT '', relative_path VARCHAR(1024) NOT NULL DEFAULT '', relative_path_sha256 CHAR(64) NULL,
    body_sha256 CHAR(64) NOT NULL DEFAULT '', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), deleted_at DATETIME(3) NULL,
    UNIQUE KEY uk_wiki_page_id (page_id), UNIQUE KEY uk_wiki_page_path (tenant_id, relative_path_sha256)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_page_sources (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    page_id VARCHAR(64) NOT NULL DEFAULT '', source_version_id BIGINT UNSIGNED NOT NULL, chunk_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL, UNIQUE KEY uk_wiki_page_source (tenant_id, page_id, source_version_id, chunk_id)
);
CREATE TABLE IF NOT EXISTS knowledge_wiki_page_relations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    from_page_id VARCHAR(64) NOT NULL DEFAULT '', to_page_id VARCHAR(64) NOT NULL DEFAULT '', relation_type VARCHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted_at DATETIME(3) NULL, UNIQUE KEY uk_wiki_relation (tenant_id, from_page_id, to_page_id, relation_type)
);
