// Package llm_wiki implements the LLM Wiki domain workflow.
package llm_wiki

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	model "github.com/ongridio/ongrid/internal/manager/model/knowledge/llm_wiki"
	"github.com/ongridio/ongrid/internal/pkg/llm"
)

const (
	SchemaVersion           = "v2"
	MaxSourceBytes          = 16 << 20
	MaxPageBytes            = 1 << 20
	TargetChunkTokens       = 4000
	HardChunkTokens         = 6000
	DefaultTenantID         = uint64(0)
	DefaultWikiWeight       = 1.5
	DefaultRawWeight        = 1.0
	PlannerPromptVersion    = "v1"
	WriterPromptVersion     = "v1"
	LeafPromptVersion       = "v2"
	ChunkCacheSchemaVersion = "v1"
	MaxCanonicalCandidates  = 5
)

type PageType string

const (
	PageTypeSource PageType = PageType(model.PageTypeSource)
	PageTypeTopic  PageType = PageType(model.PageTypeTopic)
)

type KnowledgeNodeKind string

const (
	NodeKindEntity  KnowledgeNodeKind = "entity"
	NodeKindConcept KnowledgeNodeKind = "concept"
)

type MirrorInput struct {
	TenantID   uint64
	SourceKey  string
	SourceType string
	Name       string
	Content    []byte
}

type Chunk struct {
	Ordinal int
	Start   int
	End     int
	Text    string
}

// EvidenceSpanInput is a compiler-owned source fragment that the model may
// reference by ID. The ID is scoped to one chunk.
type EvidenceSpanInput struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

// BatchChunkInput is the trusted envelope passed to a batch leaf extractor.
// ChunkID and evidence span IDs are generated by the compiler and source text
// remains untrusted data.
type BatchChunkInput struct {
	ChunkID       string              `json:"chunk_id"`
	EvidenceSpans []EvidenceSpanInput `json:"evidence_spans"`
}

type ChunkBatch struct {
	Chunks          []Chunk
	EstimatedTokens int
}

type ChunkBatchItemIR struct {
	ChunkID string         `json:"chunk_id"`
	Summary ChunkSummaryIR `json:"summary"`
}

type ChunkBatchResult struct {
	SourceSummary *ChunkSummaryIR    `json:"source_summary,omitempty"`
	Chunks        []ChunkBatchItemIR `json:"chunks"`
}

// ChunkAnalysisCache is a content-addressed, tenant-scoped leaf result. The
// content hash is deliberately exact: evidence offsets are relative to the
// original chunk text and cannot safely survive whitespace normalization.
type ChunkAnalysisCache struct {
	CacheSchema   string         `json:"cache_schema"`
	ContentHash   string         `json:"content_hash"`
	PromptVersion string         `json:"prompt_version"`
	ModelVersion  string         `json:"model_version"`
	Summary       ChunkSummaryIR `json:"summary"`
}

type EntityIR struct {
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
}

type ConceptIR struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type FactIR struct {
	Statement     string `json:"statement"`
	EvidenceStart int    `json:"evidence_start"`
	EvidenceEnd   int    `json:"evidence_end"`
}

type ConflictIR struct {
	Statement string `json:"statement"`
	With      string `json:"with"`
}

type ChunkSummaryIR struct {
	Summary   string       `json:"summary"`
	Entities  []EntityIR   `json:"entities"`
	Concepts  []ConceptIR  `json:"concepts"`
	Facts     []FactIR     `json:"facts"`
	Conflicts []ConflictIR `json:"conflicts"`
}

type ChunkRef struct {
	SourceVersionID uint64 `json:"source_version_id"`
	ChunkOrdinal    int    `json:"chunk_ordinal"`
	Start           int    `json:"start,omitempty"`
	End             int    `json:"end,omitempty"`
}

type TopicPlan struct {
	ID               string     `json:"id"`
	CanonicalKey     string     `json:"canonical_key,omitempty"`
	Title            string     `json:"title"`
	Aliases          []string   `json:"aliases,omitempty"`
	Purpose          string     `json:"purpose"`
	EntityNames      []string   `json:"entity_names,omitempty"`
	ConceptNames     []string   `json:"concept_names,omitempty"`
	SourceVersionIDs []uint64   `json:"source_version_ids"`
	ChunkRefs        []ChunkRef `json:"chunk_refs"`
	RequiredSections []string   `json:"required_sections,omitempty"`
	EvidenceTokens   int        `json:"evidence_tokens"`
	FactCount        int        `json:"fact_count"`
	ChunkCount       int        `json:"chunk_count"`
	SourceCount      int        `json:"source_count"`
	Importance       float64    `json:"importance"`
}

type TopicPlanResult struct {
	Topics []TopicPlan `json:"topics"`
}

type EvidenceRef struct {
	SourceVersionID uint64 `json:"source_version_id"`
	ChunkOrdinal    int    `json:"chunk_ordinal"`
	EvidenceStart   int    `json:"evidence_start,omitempty"`
	EvidenceEnd     int    `json:"evidence_end,omitempty"`
}

type EvidenceItem struct {
	SourceID        uint64    `json:"source_id"`
	SourceVersionID uint64    `json:"source_version_id"`
	ChunkOrdinal    int       `json:"chunk_ordinal"`
	Text            string    `json:"text"`
	SourceUpdatedAt time.Time `json:"source_updated_at"`
}

type TopicEvidence struct {
	Topic    TopicPlan      `json:"topic"`
	Evidence []EvidenceItem `json:"evidence"`
	Facts    []FactIR       `json:"facts,omitempty"`
}

type WikiSection struct {
	Title        string        `json:"title"`
	Body         string        `json:"body"`
	EvidenceRefs []EvidenceRef `json:"evidence_refs"`
}

type WikiArticle struct {
	Title       string        `json:"title"`
	Summary     string        `json:"summary"`
	Sections    []WikiSection `json:"sections"`
	Aliases     []string      `json:"aliases,omitempty"`
	Limitations []string      `json:"limitations,omitempty"`
}

type PageReviewDecision string

const (
	PageReviewKeep   PageReviewDecision = "keep"
	PageReviewMerge  PageReviewDecision = "merge"
	PageReviewExpand PageReviewDecision = "expand"
	PageReviewDrop   PageReviewDecision = "drop"
)

type PageReview struct {
	Decision PageReviewDecision `json:"decision"`
	Reason   string             `json:"reason"`
	MergeTo  string             `json:"merge_to,omitempty"`
}

type PlannerConfig struct {
	MinEvidenceTokens      int
	MinFactCount           int
	MinChunkCount          int
	MinSourceCount         int
	MinImportance          float64
	MaxTopicsPerSource     int
	MaxCanonicalCandidates int
	MaxTopicEvidenceTokens int
	MaxSectionsPerTopic    int
	LeafBatchInputTokens   int
	LeafBatchOutputTokens  int
	LeafBatchSafetyTokens  int
	EnableLeafBatch        bool
	EnableChunkCache       bool
	EnableSourceSynthesis  bool
	LeafModelVersion       string
}

func DefaultPlannerConfig() PlannerConfig {
	return PlannerConfig{
		MinEvidenceTokens: 2500, MinFactCount: 4, MinChunkCount: 3,
		MinSourceCount: 2, MinImportance: 0.8, MaxTopicsPerSource: 30,
		MaxCanonicalCandidates: MaxCanonicalCandidates,
		MaxTopicEvidenceTokens: 12000, MaxSectionsPerTopic: 12,
		LeafBatchInputTokens: 32000, LeafBatchOutputTokens: 8000,
		LeafBatchSafetyTokens: 4000, EnableLeafBatch: true,
		EnableChunkCache: true, EnableSourceSynthesis: true, LeafModelVersion: "unknown",
	}
}

type CompileStats struct {
	SourceCount        int     `json:"source_count"`
	ChunkCount         int     `json:"chunk_count"`
	CandidatePageCount int     `json:"candidate_page_count"`
	PublishedPageCount int     `json:"published_page_count"`
	DroppedPageCount   int     `json:"dropped_page_count"`
	AvgPageBytes       int     `json:"avg_page_bytes"`
	MedianPageBytes    int     `json:"median_page_bytes"`
	ThinPages500       int     `json:"thin_pages_500"`
	ThinPages1000      int     `json:"thin_pages_1000"`
	AvgSections        float64 `json:"avg_sections"`
	InputTokens        int64   `json:"input_tokens"`
	OutputTokens       int64   `json:"output_tokens"`
}

type SearchHit struct {
	Layer           string  `json:"layer"`
	PageType        string  `json:"page_type,omitempty"`
	PageID          string  `json:"page_id,omitempty"`
	SourceVersionID string  `json:"source_version_id,omitempty"`
	Title           string  `json:"title"`
	Preview         string  `json:"preview"`
	Score           float64 `json:"score"`
	MatchedNode     string  `json:"matched_node,omitempty"`
}

type IndexDocument struct {
	Page             *model.Page
	Content          string
	SourceVersionIDs []uint64
	TopicID          string
	Aliases          []string
	EntityNames      []string
	ConceptNames     []string
	SkipIndex        bool
}

// WikiPage and WikiLink are filesystem-oriented Knowledge IR types. Markdown
// is authoritative; the similarly named wiki_* SQLite rows are rebuildable
// catalog and query caches.
type WikiPage struct {
	ID             string
	Type           string
	Title          string
	Description    string
	Aliases        []string
	Language       string
	SourceVersions []uint64
	Related        []string
	RelativePath   string
	BodySHA256     string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WikiLink struct {
	FromPageID string
	ToPageID   string
	Type       string
}

type ArtifactBatch struct {
	Pages                []WikiPage
	Links                []WikiLink
	PageSourceVersionIDs map[string][]uint64
	DeletedPageIDs       []string
}

func makeArtifactBatch(pages []*model.Page, versions map[string][]uint64, relations []*model.PageRelation, deleted []string) ArtifactBatch {
	batch := ArtifactBatch{Pages: make([]WikiPage, 0, len(pages)), Links: make([]WikiLink, 0, len(relations)), PageSourceVersionIDs: versions, DeletedPageIDs: deleted}
	for _, page := range pages {
		if page == nil {
			continue
		}
		batch.Pages = append(batch.Pages, WikiPage{
			ID: page.PageID, Type: page.PageType, Title: page.Title, Aliases: decodeStringList(page.AliasesJSON),
			Language: page.Language, SourceVersions: versions[page.PageID], RelativePath: page.RelativePath,
			BodySHA256: page.BodySHA256, CreatedAt: page.CreatedAt, UpdatedAt: page.UpdatedAt,
		})
	}
	for _, relation := range relations {
		if relation != nil {
			batch.Links = append(batch.Links, WikiLink{FromPageID: relation.FromPageID, ToPageID: relation.ToPageID, Type: relation.RelationType})
		}
	}
	return batch
}

type WikiLogTopic struct {
	Path  string `json:"path"`
	Title string `json:"title"`
}

type WikiLogEvent struct {
	ID              string         `json:"id"`
	OccurredAt      time.Time      `json:"occurred_at"`
	Action          string         `json:"action"`
	Subject         string         `json:"subject"`
	SourceVersionID uint64         `json:"source_version_id,omitempty"`
	CreatedPages    int            `json:"created_pages"`
	UpdatedPages    int            `json:"updated_pages"`
	DeletedPages    int            `json:"deleted_pages"`
	Topics          []WikiLogTopic `json:"topics,omitempty"`
}

type PublishManifest struct {
	JobID                uint64                 `json:"job_id"`
	TenantID             uint64                 `json:"tenant_id"`
	SourceID             uint64                 `json:"source_id"`
	VersionID            uint64                 `json:"version_id"`
	Pages                []*model.Page          `json:"pages"`
	PageSourceVersionIDs map[string][]uint64    `json:"page_source_version_ids,omitempty"`
	Relations            []*model.PageRelation  `json:"relations"`
	Topics               []*model.Topic         `json:"topics,omitempty"`
	Evidence             []*model.TopicEvidence `json:"evidence,omitempty"`
	DeletedPages         []*model.Page          `json:"deleted_pages,omitempty"`
	LogEvent             WikiLogEvent           `json:"log_event"`
}

type TreeNode struct {
	ID            string     `json:"id"`
	ParentID      string     `json:"parent_id"`
	Layer         string     `json:"layer"`
	Kind          string     `json:"kind"`
	Name          string     `json:"name"`
	RelativePath  string     `json:"relative_path"`
	HasChildren   bool       `json:"has_children"`
	ChildCount    int        `json:"child_count"`
	DocumentCount int        `json:"document_count"`
	SourceID      string     `json:"source_id,omitempty"`
	PageID        string     `json:"page_id,omitempty"`
	PageType      string     `json:"page_type,omitempty"`
	Status        string     `json:"status,omitempty"`
	UpdatedAt     *time.Time `json:"updated_at,omitempty"`
}

type NodeDetail struct {
	TreeNode
	Content  string         `json:"content"`
	Metadata map[string]any `json:"metadata,omitempty"`
}

type NodePreview struct {
	Name        string
	ContentType string
	Content     []byte
}

type StateRepository interface {
	UpsertSourceVersion(ctx context.Context, source *model.Source, version *model.SourceVersion) (*model.Source, *model.SourceVersion, bool, error)
	ListSources(ctx context.Context, tenantID uint64, status string, limit int) ([]*model.Source, int64, error)
	GetSource(ctx context.Context, tenantID, id uint64) (*model.Source, error)
	DeleteSource(ctx context.Context, tenantID, id uint64) error
	GetVersion(ctx context.Context, tenantID, id uint64) (*model.SourceVersion, error)
	MarkVersionSchema(ctx context.Context, tenantID, id uint64, schemaVersion string) error
	CreateJob(ctx context.Context, job *model.CompileJob) error
	ListJobs(ctx context.Context, tenantID uint64, limit int) ([]*model.CompileJob, int64, error)
	GetJob(ctx context.Context, tenantID, id uint64) (*model.CompileJob, error)
	CountActiveJobs(ctx context.Context, tenantID uint64) (int64, error)
	RetryJob(ctx context.Context, tenantID, id uint64) (*model.CompileJob, error)
	CancelJob(ctx context.Context, tenantID, id uint64) (*model.CompileJob, error)
	ClaimJob(ctx context.Context, tenantID uint64, owner string, lease time.Duration) (*model.CompileJob, error)
	ClaimJobByID(ctx context.Context, tenantID, id uint64, owner string, lease time.Duration) (*model.CompileJob, error)
	UpdateJob(ctx context.Context, tenantID, id uint64, status, stage, errMessage string) error
	IsCancelRequested(ctx context.Context, tenantID, id uint64) (bool, error)
	ReplaceChunks(ctx context.Context, tenantID, versionID uint64, chunks []*model.SourceChunk) error
	ListTopics(ctx context.Context, tenantID uint64) ([]*model.Topic, error)
	GetTopic(ctx context.Context, tenantID uint64, topicID string) (*model.Topic, error)
	ListTopicEvidence(ctx context.Context, tenantID uint64, topicID string) ([]*model.TopicEvidence, error)
	ListTopicsBySource(ctx context.Context, tenantID, sourceID uint64) ([]*model.Topic, error)
	CommitTopicCompilation(ctx context.Context, tenantID, sourceID, versionID uint64, sourcePageID string, topics []*model.Topic, evidence []*model.TopicEvidence, batch ArtifactBatch) error
	MarkSourceStatus(ctx context.Context, tenantID, id uint64, status string) error
}

type WikiRepository interface {
	DeletePage(ctx context.Context, tenantID uint64, pageID string) error
	PublishPage(ctx context.Context, page *model.Page, sources []*model.PageSource) error
	ListPageSources(ctx context.Context, tenantID uint64, pageID string) ([]*model.PageSource, error)
	ListPagesBySource(ctx context.Context, tenantID, sourceID uint64) ([]*model.Page, error)
	ReplaceRelations(ctx context.Context, tenantID uint64, fromPageID string, relations []*model.PageRelation) error
	ListPages(ctx context.Context, tenantID uint64) ([]*model.Page, error)
}

type Repository interface {
	StateRepository
	WikiRepository
}

type Summarizer interface {
	Summarize(ctx context.Context, instructions, chunkID, text string) (string, error)
}

// BatchSummarizer is optional so embedders and tests that only implement the
// original single-input interface continue to work. The compiler falls back
// to single-chunk calls when this capability is unavailable.
type BatchSummarizer interface {
	SummarizeBatch(ctx context.Context, instructions string, chunks []BatchChunkInput, maxOutputTokens int) (string, llm.Usage, error)
}

// SourceSynthesizer optionally combines a complete small-source leaf batch
// into one validated source summary and topic-plan response. It is optional so
// existing embedders keep the hierarchy + planner path unchanged.
type SourceSynthesizer interface {
	SynthesizeSource(ctx context.Context, instructions, input string) (string, llm.Usage, error)
}

// VersionedSummarizer lets cache keys follow an explicitly configured model
// deployment. Implementations that do not expose a version use a conservative
// type-based fallback and can be upgraded without changing the interface.
type VersionedSummarizer interface {
	ModelVersion() string
}

// UsageSummarizer is implemented by summarizers that can return the provider
// usage for the request. The base Summarizer interface stays small so custom
// test and embedding implementations do not need to know about accounting.
type UsageSummarizer interface {
	SummarizeWithUsage(ctx context.Context, instructions, chunkID, text string) (string, llm.Usage, error)
}

// TokenUsageRecorder starts an existing chat-session transcript for one
// compile job. Implementations belong to the composition root so this domain
// does not depend directly on the AIOps bounded context.
type TokenUsageRecorder interface {
	Start(ctx context.Context, jobID uint64) (TokenUsageSink, error)
}

type TokenUsageSink interface {
	Record(ctx context.Context, usage llm.Usage) error
	Close(ctx context.Context) error
}

type SearchIndex interface {
	IndexPage(ctx context.Context, document IndexDocument) error
	DeletePage(ctx context.Context, page *model.Page) error
	Search(ctx context.Context, tenantID uint64, query string, limit int) ([]SearchHit, error)
}

type Indexer = SearchIndex

type CatalogRebuilder interface {
	Rebuild(ctx context.Context, tenantID uint64, files *FileStore) ([]string, error)
}

var ErrNoPendingJob = errors.New("no pending wiki compile job")

// CompileTriggerOption configures request-triggered asynchronous compilation.
type CompileTriggerOption struct {
	Owner   string
	Timeout time.Duration
	Limits  *PlannerConfig
}

func DecodeSourceIDs(raw string) ([]uint64, error) {
	var ids []uint64
	if err := json.Unmarshal([]byte(raw), &ids); err != nil {
		return nil, err
	}
	return ids, nil
}
